# This is the GITHUB URL where Kubernetes manifests are stored.
# If you forked this repo, you will need to update this.
repo_url: "https://github.com/livewyer-ops/cnoe-reference-implementation-gcp.git"
# Tags to apply to GCP resources
tags:
  env: "dev"
  project: "cnoe"
region: "us-east1"
# The name of the GKE cluster you are installing this under.
cluster_name: "cnoe-idp"
# Set this to false if you want to manage DNS somewhere else. e.g. manually.
enable_dns_management: true
# If using external DNS, specify the CloudDNS hosted zone ID. Required if enable_dns_management is set to true
hosted_zone_id: cnoe-dns
# if external DNS is not used, this value must be provided.
domain_name: sudbomain.domain.root

# If set to true, we will store secrets to GCP Secrets Manager, then sync it to the cluster using External Secrets Operator.
enable_external_secret: true
