apiVersion: batch/v1
kind: Job
metadata:
  name: external-dns-azure
  namespace: crossplane-system
spec:
  template:
    spec:
      serviceAccountName: upbound-controller-manager
      restartPolicy: Never
      containers:
        - name: externaldns-secret
          image: docker.io/bitnamilegacy/kubectl
          command: ["/bin/bash", "-c"]
          args:
            - |
              #! /bin/bash
              set -ex -o pipefail

              while ! kubectl get ns external-dns || ! kubectl -n external-dns get userassignedidentities.managedidentity.azure.m.upbound.io external-dns; do sleep 10; done
              kubectl -n external-dns wait --for=condition=Ready=true --timeout=600s userassignedidentities.managedidentity.azure.m.upbound.io external-dns
              while [[ $(kubectl -n external-dns get userassignedidentities.managedidentity.azure.m.upbound.io external-dns -o yaml | yq '.status.atProvider | has("clientId")') == false ]]; do sleep 10; done
              while [[ $(kubectl -n external-dns get userassignedidentities.managedidentity.azure.m.upbound.io external-dns -o yaml | yq '.status.atProvider.clientId | test("^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$")') == false ]]; do sleep 10; done

              jq -n \
                --arg clientId "$(kubectl -n external-dns get userassignedidentities.managedidentity.azure.m.upbound.io external-dns -o yaml | yq '.status.atProvider.clientId')" \
                --arg tenantId "$(kubectl -n external-dns get userassignedidentities.managedidentity.azure.m.upbound.io external-dns -o yaml | yq '.status.atProvider.tenantId')" \
                --arg resourceGroup "$(kubectl -n external-dns get userassignedidentities.managedidentity.azure.m.upbound.io external-dns -o yaml | yq '.status.atProvider.resourceGroupName')" \
                --arg subscriptionId "$(kubectl -n external-dns get userassignedidentities.managedidentity.azure.m.upbound.io external-dns -o yaml | yq '.status.atProvider.id' | awk -F/ '{print $3}')" \
                '{aadClientId: $clientId, tenantId: $tenantId, resourceGroup: $resourceGroup, subscriptionId: $subscriptionId, useWorkloadIdentityExtension: true}' > /tmp/credentials.json || exit 1

              kubectl -n external-dns create secret generic external-dns-azure --from-file=azure.json=/tmp/credentials.json || exit 1
