valueFiles:
  - "values.yaml"

syncPolicy:
  automated:
    selfHeal: false
    allowEmpty: true
    prune: false
  retry:
    limit: -1 # number of failed sync attempt retries; unlimited number of attempts if less than 0
    backoff:
      duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
      factor: 2 # a factor to multiply the base duration after each failed retry
      maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
  syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true # Big CRDs.
syncPolicyAppSet:
  preserveResourcesOnDeletion: true
useSelectors: true
repoURLGit: "{{.metadata.annotations.addonsRepoURL}}"
repoURLGitRevision: "{{.metadata.annotations.addonsRepoRevision}}"
repoURLGitBasePath: "{{.metadata.annotations.addonsRepoBasepath}}"
# valueFiles:
#   - default/addons
#   - clusters/{{.metadata.labels.environment}}/addons
#   - clusters/{{.nameNormalized}}/addons
useValuesFilePrefix: false
# valuesFilePrefix: '{{.metadata.labels.tenant}}/'
# ackPodIdentity:
#   path: "charts/pod-identity"
#appsetPrefix: "appset-"
