# YAML Schema for config.yaml

repo:
  url: str()
  revision: str()
  basepath: str()
cluster_name: str()
subscription: regex('^[a-z0-9\\-]{4,}$')
location: str()
resource_group: str()
tenant_id: regex('^[a-z0-9\\-]{4,}$')
cluster_oidc_issuer_url: regex('^http(s?)://.*$')
domain: str()
keyvault: str()
path_routing: bool()
github:
  appId: regex('^[0-9]+$')
  installationId: regex('^[0-9]+$')
  orgURL: regex('^http(s?)://.*$')
  clientId: regex('^[a-zA-Z0-9]+$')
  clientSecret: regex('^[a-zA-Z0-9]{32,}')
  webhookUrl: regex('^http(s?)://.*$')
  webhookSecret: str()
  privateKey: str(multiline=True)
letsencrypt_env: enum('prod', 'staging')
tags: map(str(), key=str())
