apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: keycloak
  name: eso-store
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-store
  namespace: keycloak
subjects:
  - kind: ServiceAccount
    name: external-secrets-sa
    namespace: external-secrets
roleRef:
  kind: Role
  name: eso-store
  apiGroup: rbac.authorization.k8s.io
