apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-azure
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: external-dns-azure
    template:
      data:
        azure.json: |
          {
            "aadClientId": "{{ .aadClientId }}",
            "tenantId": "{{ .tenantId }}",
            "subscriptionId": "{{ .subscriptionId }}",
            "resourceGroup": "{{ .resourceGroup }}",
            "useWorkloadIdentityExtension": true
          }
  data:
    - secretKey: aadClientId
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: config
        property: externaldns_workload_identity.clientId
        metadataPolicy: None
    - secretKey: tenantId
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: config
        property: externaldns_workload_identity.tenantId
        metadataPolicy: None
    - secretKey: subscriptionId
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: config
        property: subscription
        metadataPolicy: None
    - secretKey: resourceGroup
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: config
        property: resource_group
        metadataPolicy: None
