# in-cluster ArgoCD cluster Secret for passing metadata to ApplicationSets

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: hub-cluster-secret
  namespace: argocd
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: cnoe
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
          environment: "control-plane"
        annotations:
          addonsRepoURL: "{{ .addonsRepoURL }}"
          addonsRepoRevision: "{{ .addonsRepoRevision }}"
          addonsRepoBasepath: "{{ .addonsRepoBasepath }}"
          subscription: "{{ .subscription }}"
          tenantId: "{{ .tenantId }}"
          location: "{{ .location }}"
          resourceGroup: "{{ .resourceGroup }}"
          clusterName: "{{ .clusterName }}"
          clusterOIDCIssuerURL: "{{ .clusterOIDCIssuerURL }}"
          domain: "{{ .domain }}"
          keyvault: "{{ .keyvault }}"
          pathRouting: "{{ .pathRouting }}"
          environment: "control-plane"
          crossplaneClientId: "{{ .crossplaneClientId }}"
          crossplaneTenantId: "{{ .crossplaneTenantId }}"
          letsencryptEnv: "{{ .letsencryptEnv }}"
      data:
        name: "{{ .clusterName }}"
        server: https://kubernetes.default.svc
  data:
    - secretKey: addonsRepoURL
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: config
        property: repo.url
        metadataPolicy: None
    - secretKey: addonsRepoRevision
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: config
        property: repo.revision
        metadataPolicy: None
    - secretKey: addonsRepoBasepath
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: config
        property: repo.basepath
        metadataPolicy: None
    - secretKey: subscription
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: config
        property: subscription
        metadataPolicy: None
    - secretKey: tenantId
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: config
        property: tenant_id
        metadataPolicy: None
    - secretKey: location
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: config
        property: location
        metadataPolicy: None
    - secretKey: resourceGroup
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: config
        property: resource_group
        metadataPolicy: None
    - secretKey: clusterName
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: config
        property: cluster_name
        metadataPolicy: None
    - secretKey: clusterOIDCIssuerURL
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: config
        property: cluster_oidc_issuer_url
        metadataPolicy: None
    - secretKey: domain
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: config
        property: domain
        metadataPolicy: None
    - secretKey: keyvault
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: config
        property: keyvault
        metadataPolicy: None
    - secretKey: pathRouting
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: config
        property: path_routing
        metadataPolicy: None
    - secretKey: letsencryptEnv
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: config
        property: letsencrypt_env
        metadataPolicy: None
    - secretKey: crossplaneClientId
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: crossplane-azwi
        property: clientId
        metadataPolicy: None
    - secretKey: crossplaneTenantId
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: crossplane-azwi
        property: tenantId
        metadataPolicy: None
