apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: provider-gcp-config
  annotations:
    iam.gke.io/gcp-service-account: ${GCP_ROLE}
spec:
  podSecurityContext:
    fsGroup: 2000
  args:
    - --debug
    - --enable-management-policies
