apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: keycloak
  namespace: keycloak
spec:
  provider:
    gcpsm:
      projectID: ${PROJECT_ID}
      auth:
        workloadIdentity:
          clusterLocation: ${GCP_LOCATION}
          clusterName: ${GKE_CLUSTER}
          serviceAccountRef:
            name: ${KSA}
