apiVersion: azure.livewyer.io/v1alpha1
kind: WorkloadIdentity
metadata:
  name: external-dns
  namespace: external-dns
spec:
  forProvider:
    location: "{{ .location }}"
    oidcIssuerURL: "{{ .clusterOIDCIssuerURL }}"
    resourceGroupName: "{{ .resourceGroup }}"
    roleAssignments:
      - roleDefinitionName: DNS Zone Contributor
        scope: "{{ .resourceGroup }}"
      - roleDefinitionName: Reader
        scope: "{{ .resourceGroup }}"
    serviceAccountName: external-dns
