apiVersion: azure.livewyer.io/v1alpha1
kind: WorkloadIdentity
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  forProvider:
    location: "{{ .location }}"
    oidcIssuerURL: "{{ .clusterOIDCIssuerURL }}"
    resourceGroupName: "{{ .resourceGroup }}"
    roleAssignments:
      - roleDefinitionName: Key Vault Secrets User
        scope: "{{ .subscription }}/resourcegroups/resource-{{ .resourceGroup }}"
    serviceAccountName: external-secrets
