apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      vaultUrl: https://cnoe-ref-impl.vault.azure.net
      serviceAccountRef:
        name: external-secrets
