argocd:
  enabled: true
  chartName: argo-cd
  namespace: argocd
  releaseName: argocd
  defaultVersion: "8.0.14"
  chartRepository: "https://argoproj.github.io/argo-helm"
  valuesObject:
    global:
      domain: '{{ if eq .metadata.annotations.pathRouting "true" }}{{ .metadata.annotations.domain }}{{ else }}argocd.{{ .metadata.annotations.domain }}{{ end }}'
    server:
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: '{{ if eq .metadata.annotations.pathRouting "false" }}letsencrypt-prod{{ end }}'
        path: '/{{ if eq .metadata.annotations.pathRouting "true" }}argocd{{ end }}'
    configs:
      cm:
        oidc.config: |
          name: Keycloak
          issuer: https://{{ if eq .metadata.annotations.pathRouting "false" }}keycloak.{{ .metadata.annotations.domain }}{{ else }}{{ .metadata.annotations.domain }}/keycloak{{ end }}/realms/cnoe
          clientID: argocd
          enablePKCEAuthentication: true
          requestedScopes:
            - openid
            - profile
            - email
            - groups
      params:
        "server.basehref": '/{{ if eq .metadata.annotations.pathRouting "true" }}argocd{{ end }}'
        "server.rootpath": '{{ if eq .metadata.annotations.pathRouting "true" }}argocd{{ end }}'
  additionalResources:
    - manifestPath: "manifests"
      type: "manifests"
  selector:
    matchExpressions:
      - key: environment
        operator: In
        values: ["control-plane-bootstrap", "control-plane"]

crossplane:
  enabled: true
  chartName: crossplane
  namespace: crossplane-system
  releaseName: crossplane
  defaultVersion: "2.0.2-up.4"
  chartRepository: "https://charts.upbound.io/stable"
  selector:
    matchExpressions:
      - key: environment
        operator: In
        values: ["control-plane"]

crossplane-config:
  enabled: true
  chartName: raw
  namespace: crossplane-system
  releaseName: crossplane-xrs
  defaultVersion: "0.1.0"
  chartRepository: "{{ .metadata.annotations.addonsRepoURL }}"
  path: packages/charts/raw
  valuesObject:
    templates:
      - apiVersion: azure.m.upbound.io/v1beta1
        kind: ClusterProviderConfig
        metadata:
          name: default
        spec:
          credentials:
            source: Secret
            secretRef:
              name: provider-azure
              namespace: crossplane-system
              key: credentials
      - apiVersion: kubernetes.m.crossplane.io/v1alpha1
        kind: ClusterProviderConfig
        metadata:
          name: default
          namespace: crossplane-system
        spec:
          credentials:
            source: InjectedIdentity
  selector:
    matchExpressions:
      - key: environment
        operator: In
        values: ["control-plane"]

crossplane-xrs:
  enabled: true
  chartName: raw
  namespace: crossplane-system
  releaseName: crossplane-xrs
  defaultVersion: "0.1.0"
  chartRepository: "{{ .metadata.annotations.addonsRepoURL }}"
  path: packages/charts/raw
  valuesObject:
    templates:
      - apiVersion: azure.livewyer.io/v1alpha1
        kind: WorkloadIdentity
        metadata:
          name: external-dns
          namespace: external-dns
        spec:
          forProvider:
            location: "{{ .metadata.annotations.location }}"
            oidcIssuerURL: "{{ .metadata.annotations.clusterOIDCIssuerURL }}"
            resourceGroupName: "{{ .metadata.annotations.resourceGroup }}"
            roleAssignments:
              - roleDefinitionName: DNS Zone Contributor
                scope: "/subscriptions/{{ .metadata.annotations.subscription }}/resourcegroups/{{ .metadata.annotations.resourceGroup }}"
              - roleDefinitionName: Reader
                scope: "/subscriptions/{{ .metadata.annotations.subscription }}/resourcegroups/{{ .metadata.annotations.resourceGroup }}"
            serviceAccountName: external-dns
      - apiVersion: azure.livewyer.io/v1alpha1
        kind: WorkloadIdentity
        metadata:
          name: external-secrets
          namespace: external-secrets
        spec:
          forProvider:
            location: "{{ .metadata.annotations.location }}"
            oidcIssuerURL: "{{ .metadata.annotations.clusterOIDCIssuerURL }}"
            resourceGroupName: "{{ .metadata.annotations.resourceGroup }}"
            roleAssignments:
              - roleDefinitionName: Key Vault Secrets User
                scope: "/subscriptions/{{ .metadata.annotations.subscription }}/resourcegroups/{{ .metadata.annotations.resourceGroup }}"
            serviceAccountName: external-secrets
      - apiVersion: azure.livewyer.io/v1alpha1
        kind: WorkloadIdentity
        metadata:
          name: keycloak-eso-store
          namespace: keycloak
        spec:
          forProvider:
            location: "{{ .metadata.annotations.location }}"
            oidcIssuerURL: "{{ .metadata.annotations.clusterOIDCIssuerURL }}"
            resourceGroupName: "{{ .metadata.annotations.resourceGroup }}"
            roleAssignments:
              - roleDefinitionName: Key Vault Secrets User
                scope: "/subscriptions/{{ .metadata.annotations.subscription }}/resourcegroups/{{ .metadata.annotations.resourceGroup }}"
              - roleDefinitionName: Key Vault Reader
                scope: "/subscriptions/{{ .metadata.annotations.subscription }}/resourcegroups/{{ .metadata.annotations.resourceGroup }}"
            serviceAccountName: eso-store
  selector:
    matchExpressions:
      - key: environment
        operator: In
        values: ["control-plane"]

ingress-nginx:
  enabled: true
  chartName: ingress-nginx
  namespace: ingress-nginx
  releaseName: ingress-nginx
  defaultVersion: "4.7.0"
  chartRepository: "https://kubernetes.github.io/ingress-nginx"
  selector:
    matchExpressions:
      - key: environment
        operator: In
        values: ["control-plane"]

external-dns:
  enabled: true
  releaseName: external-dns
  namespace: external-dns
  chartName: external-dns
  chartRepository: https://kubernetes-sigs.github.io/external-dns
  defaultVersion: "1.16.1"
  valuesObject:
    provider:
      name: azure
    domainFilters:
      - "{{ .metadata.annotations.domain }}"
  selector:
    matchExpressions:
      - key: environment
        operator: In
        values: ["control-plane"]

external-secrets:
  enabled: true
  enableAckPodIdentity: false
  namespace: external-secrets
  chartName: external-secrets
  defaultVersion: "0.17.0"
  chartRepository: "https://charts.external-secrets.io"
  additionalResources:
    - manifestPath: "manifests"
      type: "manifests"
  selector:
    matchExpressions:
      - key: environment
        operator: In
        values: ["control-plane-bootstrap", "control-plane"]

cert-manager:
  enabled: true
  chartName: cert-manager
  namespace: cert-manager
  releaseName: cert-manager
  defaultVersion: "1.17.2"
  chartRepository: "https://charts.jetstack.io"
  valuesObject:
    global:
      domainName: '{{ if eq .metadata.annotations.pathRouting "true" }}{{ .metadata.annotations.domain }}{{ end }}'
      pathRouting: '{{ if eq .metadata.annotations.pathRouting "true" }}true{{ else }}false{{ end }}'
  selector:
    matchExpressions:
      - key: environment
        operator: In
        values: ["control-plane"]

keycloak:
  enabled: true
  chartName: keycloak
  namespace: keycloak
  releaseName: keycloak
  defaultVersion: "24.7.3"
  chartRepository: "https://charts.bitnami.com/bitnami"
  valuesObject:
    httpRelativePath: '/{{ if eq .metadata.annotations.pathRouting "true" }}keycloak/{{ end }}'
    ingress:
      hostname: '{{ if eq .metadata.annotations.pathRouting "false" }}keycloak.{{ .metadata.annotations.domain }}{{ else }}{{ .metadata.annotations.domain }}{{ end }}'
      annotations:
        cert-manager.io/cluster-issuer: '{{ if eq .metadata.annotations.pathRouting "false" }}letsencrypt-prod{{ end }}'
      extraTls:
        - hosts:
            - '{{ if eq .metadata.annotations.pathRouting "false" }}keycloak.{{ .metadata.annotations.domain }}{{ else }}{{ .metadata.annotations.domain }}{{ end }}'
          secretName: keycloak-server-tls
  additionalResources:
    - manifestPath: "manifests"
      type: "manifests"
  selector:
    matchExpressions:
      - key: environment
        operator: In
        values: ["control-plane"]

backstage:
  enabled: true
  chartName: backstage
  namespace: backstage
  releaseName: backstage
  defaultVersion: "2.6.0"
  chartRepository: "https://backstage.github.io/charts"
  valuesObject:
    ingress:
      host: '{{ if eq .metadata.annotations.pathRouting "false" }}backstage.{{ .metadata.annotations.domain }}{{ else }}{{ .metadata.annotations.domain }}{{ end }}'
      annotations:
        cert-manager.io/cluster-issuer: '{{ if eq .metadata.annotations.pathRouting "false" }}letsencrypt-prod{{ end }}'
    backstage:
      appConfig:
        catalog:
          locations:
            - type: url
              target: "{{ .metadata.annotations.addonsRepoURL }}/blob/{{ .metadata.annotations.addonsRepoRevision }}/templates/backstage/catalog-info.yaml"
      extraEnvVars:
        - name: BACKSTAGE_FRONTEND_URL
          value: 'https://{{ if eq .metadata.annotations.pathRouting "false" }}backstage.{{ .metadata.annotations.domain }}{{ else }}{{ .metadata.annotations.domain }}{{ end }}'
        - name: KEYCLOAK_NAME_METADATA
          value: 'https://{{ if eq .metadata.annotations.pathRouting "false" }}keycloak.{{ .metadata.annotations.domain }}{{ else }}{{ .metadata.annotations.domain }}/keycloak{{ end }}/realms/cnoe/.well-known/openid-configuration'
        - name: ARGO_WORKFLOWS_URL
          value: 'https://{{ if eq .metadata.annotations.pathRouting "false" }}argo-workflows.{{ .metadata.annotations.domain }}{{ else }}{{ .metadata.annotations.domain }}/argo-workflows{{ end }}'
        - name: ARGO_CD_URL
          value: 'https://{{ if eq .metadata.annotations.pathRouting "false" }}argocd.{{ .metadata.annotations.domain }}{{ else }}{{ .metadata.annotations.domain }}/argocd{{ end }}'
  additionalResources:
    - manifestPath: "manifests"
      type: "manifests"
  selector:
    matchExpressions:
      - key: environment
        operator: In
        values: ["control-plane"]

argo-workflows:
  enabled: true
  chartName: argo-workflows
  namespace: argo
  releaseName: argo-workflows
  defaultVersion: "0.45.18"
  chartRepository: "https://argoproj.github.io/argo-helm"
  valuesObject:
    server:
      baseHref: '/{{ if eq .metadata.annotations.pathRouting "true" }}argo-workflows/{{ end }}'
      sso:
        issuer: '{{ if eq .metadata.annotations.pathRouting "true" }}https://{{ .metadata.annotations.domain }}/keycloak{{ else }}https://keycloak.{{ .metadata.annotations.domain }}{{ end }}/realms/cnoe'
        redirectUrl: '{{ if eq .metadata.annotations.pathRouting "true" }}https://{{ .metadata.annotations.domain }}/argo-workflows{{ else }}https://argo-workflows.{{ .metadata.annotations.domain }}{{ end }}/oauth2/callback'
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: '{{ if eq .metadata.annotations.pathRouting "false" }}letsencrypt-prod{{ end }}'
          nginx.ingress.kubernetes.io/rewrite-target: '{{ if eq .metadata.annotations.pathRouting "true" }}/$2{{ end }}'
        hosts:
          - '{{ if eq .metadata.annotations.pathRouting "true" }}{{ .metadata.annotations.domain }}{{ else }}argo-workflows.{{ .metadata.annotations.domain }}{{ end }}'
        paths:
          - '/{{ if eq .metadata.annotations.pathRouting "true" }}argo-workflows(/|$)(.*){{ end }}'
        tls:
          - hosts:
              - '{{ if eq .metadata.annotations.pathRouting "true" }}{{ .metadata.annotations.domain }}{{ else }}argo-workflows.{{ .metadata.annotations.domain }}{{ end }}'
            secretName: argo-workflows-server-tls
  additionalResources:
    - manifestPath: "manifests"
      type: "manifests"
  selector:
    matchExpressions:
      - key: environment
        operator: In
        values: ["control-plane"]

syncPolicy:
  automated:
    selfHeal: true
    allowEmpty: true
    prune: false

syncPolicyAppSet:
  preserveResourcesOnDeletion: false # Set to false so that cleanup script removes all the deployed resources
