apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-gcp-config
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  projectID: ${PROJECT_ID}
  credentials:
    source: InjectedIdentity
